apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: getting-started-bgd-app
  namespace: argocd
spec:
  destination:
    namespace: getting-started
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/getting-started-bgd
    repoURL: https://gitlab.com/Alexander_Gonzalez_Ferreiro/project-ci-cd-bg-daniel_alexander.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
