kind: Service
apiVersion: v1
metadata:
  name:  getting-started-rollout-svc-preview
spec:
  selector:
    app:  getting-started-rollout
  type:  ClusterIP
  ports:
  - name:  http
    port:  8080
    targetPort:  8080