apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: getting-started-rollout
 
nameSuffix: -geba
namePrefix: prod-
 
commonLabels:
  app: getting-started-rollout
  version: v1
  env: prod
 
 
configurations:
  - https://argoproj.github.io/argo-rollouts/features/kustomize/rollout-transform.yaml
 
resources:
  - getting-started-rollout-ns.yaml
  - rollout.yaml
  - getting-started-rollout-svc-active.yaml
  - getting-started-rollout-svc-preview.yaml